# Generated by Django 2.2.17 on 2020-12-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tamil', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('Application_No', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='register.Student', verbose_name='ApplicationNo')),
            ],
        ),
    ]
