# Generated by Django 3.1.4 on 2020-12-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '__first__'),
        ('mark', '0002_auto_20201219_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='Application_No',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='register.student', verbose_name='Name'),
        ),
    ]
